### ISSUE TITLE
TLS setting in config file is ignored

### ISSUE THREAD

**Issue by nextmat** [papertrail/remote_syslog2#141]
With a config file like:

```yaml
files:
  - /export/sites/*/log/*.log
destination:
  host: logs.papertrailapp.com
  port: <myport>
  protocol: tls
exclude_patterns:
  - don't log on me
```

Running with just the config file:
```sh
$ remote_syslog -c /usr/etc/log_files.yml -D
Watching 2 files/globs. Sending to logs.papertrailapp.com:<port> (UDP)
```

But `--tls` command-line option is respected:
```sh
remote_syslog -c /usr/etc/log_files.yml -D --tls
Watching 2 files/globs. Sending to logs.papertrailapp.com:<port> (TCP/TLS).
```
