### ISSUE TITLE
Parse Environment Variables located inside log_files.yml

### ISSUE THREAD

**Issue by johlym** [papertrail/remote_syslog2#172]
Submitting this on behalf of a user. When deploying remote_syslog2 in an automated fashion, it helps to be able to use environment variables to automatically point remote_syslog2 in the right direction toward the log files of the application. 

Example

```

files: 
- <%= ENV['MY_VAR'] %>/path/to/logfile.log 
- <%= ENV['MY_VAR'] %>/path/to/second.log 

destination: 
  host: logs.papertrailapp.com 
  port: 12345 
  protocol: tls
```

Note: the tags are ERB but we could possibly come up with a standard implementation of this.
