### ISSUE TITLE
How to setup Token based destination in config

### ISSUE THREAD

**Issue by abhi-nestegg** [papertrail/remote_syslog2#235]
I am trying to setup Token based destination for my logs. However, cannot find any example config for the same.
I am using Elastic Beanstalk, so it would be great if a sample configuration can be shared for the same.

**Comment by markdascher** [comment]
We've just added token support in #239. There aren't many examples yet, but basically you'll just start with a regular config, but then replace the `destination` section with:

```yml
destination:
  host: logs.collector.solarwinds.com
  port: 6514
  protocol: tls
  token: YOUR-TOKEN-HERE
```

Does that make sense? I'll leave this issue open until we have it more thoroughly documented.

Also be sure to use the latest release, at least [v0.21-beta1](https://github.com/papertrail/remote_syslog2/releases) or later.
