### ISSUE TITLE
Display an error if a particular config line is malformed

### ISSUE THREAD

**Issue by leonsodhi** [papertrail/remote_syslog2#43]
Currently, r_s2 won't complain if the following config is used:

```
files:
  /home/leon/test.log
destination:
  host: HOST.papertrailapp.com
  port: PORT
  protocol: tls
```

Output:

```
sudo ./remote_syslog -c ./example_config.yml -D
2014-10-09 18:38:13 INFO  remote_syslog.go:114 Connecting to HOST.papertrailapp.com:PORT over tls
```

No files are being monitored but it's not clear why that's the case.
