### ISSUE TITLE
If port is given in quotes in the config file, it is silently ignored

### ISSUE THREAD

**Issue by kierenevans** [papertrail/remote_syslog2#84]
Hi,

We encountered an issue when setting the configuration file up with chef whereby if the port number is specified in single quotes, it is silently ignored and the default of 514 is used.

I have submitted a PR to fix the quoted port with the chef cookbook in question ( https://github.com/trappar/remote_syslog2-cookbook/pull/2 ) but thought I should also raise it here.

With a config file like so at `/etc/remote_syslog2.yml`:

```
---
files: []
exclude_files: []
exclude_patterns: []
hostname: foo.example.com
destination:
  host: logs2.papertrailapp.com
  port: '1234'
  protocol: tls
```

and when launched like so: `sudo /usr/local/bin/remote_syslog2 -c /etc/remote_syslog2.yml --pid-file=/var/run/remote_syslog2.pid -D`, the following is outputted:

```
2015-08-11 10:02:24 INFO  remote_syslog.go:114 Connecting to logs2.papertrailapp.com:514 over tls
2015-08-11 10:02:24 CRITICAL  remote_syslog.go:118 Cannot connect to server: dial tcp 173.247.105.170:514: connection refused
```

This immediately fails as logs2.papertrailapp.com isn't open for tcp connections to port 514.
